import { writeFileSync } from 'node:fs';

import { expect, test, type Locator } from '@playwright/test';

import { CORPUS, FIXED_NOW } from './fixtures/corpus.ts';
import { seedDatabase } from './fixtures/seed.ts';

/**
 * Records the shipped app's real geometry and typography, surface by surface,
 * into `docs/design/measurements.md`.
 *
 * This is the other half of the design harness. `shots.spec.ts` answers "what
 * does it look like"; this answers "what is it, in numbers" — so a restyle can
 * be specified as a target value and checked against the previous run instead
 * of being nudged by eye until it feels right. It is also the only place the
 * two apps can be compared quantitatively: Bear's numbers are measured by hand
 * and recorded alongside these in `docs/design/DESIGN-bear-web.md`.
 *
 * Like the shots harness it asserts nothing and is excluded from
 * `npm run test:e2e`; run it with `npm run measure`. It reads only computed
 * style, so it cannot fail a build — a surface that disappears is reported as
 * `missing` rather than throwing, because a partial measurement is still worth
 * having and a restyle in progress routinely has one.
 */

const PROPERTIES = [
  'font-family',
  'font-size',
  'font-weight',
  'line-height',
  'letter-spacing',
  'color',
  'background-color',
  'padding',
  'margin',
  'border-radius',
  'border-top-width',
  'border-bottom-width',
  'gap',
  'max-width',
  'box-shadow',
] as const;

interface Measurement {
  surface: string;
  note: string;
  box: { width: number; height: number } | 'missing';
  style: Record<string, string>;
}

async function measure(target: Locator, surface: string, note: string): Promise<Measurement> {
  if ((await target.count()) === 0) {
    return { surface, note, box: 'missing', style: {} };
  }

  const first = target.first();
  const box = await first.boundingBox();
  const style = await first.evaluate((element, properties) => {
    const computed = getComputedStyle(element);
    const result: Record<string, string> = {};
    for (const property of properties) result[property] = computed.getPropertyValue(property);
    return result;
  }, PROPERTIES);

  return {
    surface,
    note,
    box: box === null ? 'missing' : { width: round(box.width), height: round(box.height) },
    style,
  };
}

/** Sub-pixel layout is real but not actionable; a tenth of a pixel is. */
function round(value: number): number {
  return Math.round(value * 10) / 10;
}

/**
 * Only the properties that differ from the surface above are printed. A table
 * in which every row repeats the same font stack is unreadable, and the whole
 * point of this file is that a human compares two columns of it.
 */
function toMarkdown(measurements: Measurement[]): string {
  const lines: string[] = [
    '<!-- Generated by `npm run measure`. Do not edit by hand. -->',
    '',
    '# bear-web measured',
    '',
    'The shipped app, measured through a real browser at 1440x900 in Paper, against',
    'the corpus in `e2e/fixtures/corpus.ts`. Regenerate with `npm run measure`.',
    '',
    "Bear's own numbers belong beside these in `docs/design/DESIGN-bear-web.md`;",
    'this file is only ever one side of that comparison.',
    '',
  ];

  for (const item of measurements) {
    lines.push(`## ${item.surface}`, '');
    lines.push(`${item.note}`, '');

    if (item.box === 'missing') {
      lines.push('**Not present in the rendered app.**', '');
      continue;
    }

    lines.push(`| Property | Value |`, `| --- | --- |`);
    lines.push(`| box | ${String(item.box.width)} x ${String(item.box.height)} |`);
    for (const [property, value] of Object.entries(item.style)) {
      if (value === '' || value === 'none' || value === 'normal' || value === '0px') continue;
      lines.push(`| ${property} | \`${value}\` |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Measures the note-list row at each preview density, driving the menu the way
 * a user would rather than writing the setting directly — the same reason
 * `shots.spec.ts` selects themes through the paint-time mirror. A measurement
 * taken from a state the app cannot actually reach is not a measurement of the
 * app.
 */
async function measureRowDensities(
  page: import('@playwright/test').Page,
  list: Locator,
): Promise<Measurement[]> {
  const sizes = [
    { label: 'Small', lines: 'no snippet line' },
    { label: 'Medium', lines: 'one snippet line' },
    { label: 'Large', lines: 'two snippet lines' },
  ] as const;
  const out: Measurement[] = [];

  for (const size of sizes) {
    await list.getByRole('button', { name: /^List options/ }).click();
    await page.getByRole('menuitemradio', { name: size.label }).click();
    await page.keyboard.press('Escape');
    out.push(
      await measure(
        list.getByRole('listitem').nth(2),
        `note list: row (${size.label.toLowerCase()})`,
        `Preview density ${size.label.toLowerCase()}: ${size.lines}, its height reserved. The step between these three is the reserved snippet height.`,
      ),
    );
  }

  // Back to the default, so every surface measured after this one is measured
  // in the state the app ships in.
  await list.getByRole('button', { name: /^List options/ }).click();
  await page.getByRole('menuitemradio', { name: 'Large' }).click();
  await page.keyboard.press('Escape');

  return out;
}

test.describe('@measure', () => {
  test.use({
    viewport: { width: 1440, height: 900 },
    colorScheme: 'light',
    locale: 'en-US',
    timezoneId: 'Asia/Seoul',
  });

  test('records the shipped geometry @measure', async ({ page }) => {
    await page.clock.setFixedTime(FIXED_NOW);
    await seedDatabase(page, CORPUS);
    await page.goto('/');

    const sidebar = page.getByRole('region', { name: 'Sidebar' });
    const list = page.getByRole('region', { name: 'Note list' });
    const editor = page.getByRole('region', { name: 'Editor' });

    await expect(page.getByRole('button', { name: /US market daily/ })).toBeVisible();
    await expect(sidebar.getByText('economy')).toBeVisible();
    await page.getByRole('button', { name: /US market daily/ }).click();
    await expect(editor).toContainText('One-line summary');
    await page.evaluate(() => document.fonts.ready);

    const prose = editor.locator('.ProseMirror');

    const measurements = [
      await measure(
        page.locator('main'),
        'shell',
        'The ground the panes float on. Its padding is the outer inset.',
      ),
      await measure(sidebar, 'pane: sidebar', 'Width is durable, from the settings table.'),
      await measure(list, 'pane: note list', 'Width is durable, from the settings table.'),
      await measure(editor, 'pane: editor', 'Fills the remaining space so the toolbars span it.'),
      await measure(
        page.locator('[aria-label="Resize the sidebar"]'),
        'resizer',
        'The gap between cards IS the resizer.',
      ),

      await measure(
        sidebar.getByRole('navigation', { name: 'Lists' }),
        'sidebar: smart list group',
        'All seven builtins, rendered as data.',
      ),
      await measure(
        sidebar.getByRole('button', { name: /^Notes/ }),
        'sidebar: smart list row',
        "The workhorse row. Bear's equivalent is the density benchmark.",
      ),
      await measure(
        sidebar.getByRole('button', { name: /^dev/ }),
        'sidebar: tag row (depth 0)',
        'A root tag.',
      ),
      await measure(
        sidebar.getByRole('button', { name: /^us-market/ }),
        'sidebar: tag row (depth 1)',
        'A nested tag. Compare padding-left against depth 0 for the indent step.',
      ),

      await measure(
        list.getByRole('button', { name: /^List options/ }),
        'note list: scope header button',
        'Names the active scope and opens the options menu. Bear puts its own at the same corner.',
      ),
      await measure(
        list.getByRole('searchbox'),
        'note list: search field',
        'Native cancel widget suppressed; our own clear button instead.',
      ),
      await measure(
        list.getByRole('listitem').first(),
        'note list: row (selected)',
        'Three stacked lines. Bear fits a two-line snippet in comparable height.',
      ),
      await measure(
        list.getByRole('listitem').nth(2),
        'note list: row (resting)',
        'Unselected, for the divider and hover baseline.',
      ),
      // The three densities, measured at the same row so the heights are
      // directly comparable. Each size reserves its own snippet height rather
      // than sharing one constant, so these three numbers ARE the feature.
      ...(await measureRowDensities(page, list)),

      await measure(
        editor.getByRole('toolbar', { name: 'Top controls' }),
        'editor: top controls',
        'Currently a full-width bar; Bear floats a pill group here.',
      ),
      await measure(
        editor.getByRole('toolbar', { name: 'Formatting toolbar' }),
        'editor: bottom toolbar',
        'Currently welded to the window edge; Bear floats a centred rounded bar.',
      ),
      await measure(
        prose,
        'editor: prose column',
        'min-width is 12rem (a floor); max-width is min(--bear-line-width, 100% - 3rem). The token alone only decides the box above roughly 688px of pane width; narrower panes reserve margin for the fold gutter instead, down to the 12rem floor. Compare box width against the pane width, not just the token, to tell which rule is engaging.',
      ),
      await measure(prose.locator('h1').first(), 'editor: h1', 'The note title line.'),
      await measure(prose.locator('h2').first(), 'editor: h2', ''),
      await measure(prose.locator('h3').first(), 'editor: h3', ''),
      await measure(
        prose.locator('p').first(),
        'editor: paragraph',
        'The measure the whole page is set against.',
      ),
      await measure(prose.locator('blockquote'), 'editor: blockquote', ''),
      await measure(
        prose.locator('pre'),
        'editor: code block',
        'Also what an unsupported construct — a table — currently renders as.',
      ),
      await measure(
        prose.locator('.bear-tag').first(),
        'editor: tag pill',
        'A decoration, not a mark.',
      ),
      await measure(prose.locator('ul[data-type="taskList"] li').first(), 'editor: task item', ''),
    ];

    // L3's graph REPLACES the three panes rather than sitting beside them, so
    // this has to be measured last: opening it makes `sidebar`, `list` and
    // `editor` above disappear for the rest of the test.
    await page.keyboard.press('ControlOrMeta+Shift+G');
    await expect(page.getByRole('img')).toBeVisible();
    measurements.push(
      await measure(
        page.locator('header'),
        'graph: header',
        'Back, title, and the summary toggle. The graph is the one surface that replaces the three panes rather than sitting beside them.',
      ),
    );

    writeFileSync('docs/design/measurements.md', toMarkdown(measurements));
    writeFileSync('docs/design/measurements.json', `${JSON.stringify(measurements, null, 2)}\n`);
  });
});
